# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_student_realname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='follow',
            name='name',
            field=models.CharField(default='student1', max_length=50),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(default='Medical Health', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='realname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(default='Math', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='ntu', max_length=50),
        ),
    ]
