# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160822_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='follow',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='badge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Badge'),
        ),
        migrations.AlterField(
            model_name='student',
            name='follow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Follow'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
