# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160822_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('student1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='profiles.Student')),
                ('student2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='profiles.Student')),
            ],
        ),
    ]
