# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160822_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='student',
            field=models.ManyToManyField(to='profiles.Student'),
        ),
    ]
