# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Interest'),
        ),
        migrations.AlterField(
            model_name='student',
            name='talent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Talent'),
        ),
    ]
