# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20160901_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='student',
        ),
        migrations.AlterField(
            model_name='team',
            name='need',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
