# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20160831_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='roomname',
        ),
    ]
