# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_chatroom_roomname'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=50)),
                ('upload_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='up_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_datetime', models.DateTimeField()),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='file_info',
            name='File',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.up_file'),
        ),
    ]
