# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20160904_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_file',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Student'),
        ),
    ]
