# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20160903_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Student', unique=True),
        ),
    ]
