# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_up_file_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up_file',
            name='content',
        ),
    ]
