# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20160903_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Student'),
        ),
    ]
