# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20160903_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
                ('followee', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Follow'),
        ),
    ]
