# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20160903_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='students',
            field=models.ManyToManyField(to='profiles.Student'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
