# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20160903_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='follow',
            field=models.ManyToManyField(related_name='_student_follow_+', to='profiles.Student'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
