# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20160903_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='_student_follow_+', to='profiles.Student'),
        ),
    ]
